---
- name: Deploy arr stack
  ansible.builtin.include_tasks: deploy.yml

- name: Configure qBittorrent
  ansible.builtin.include_tasks: qbittorrent.yml

- name: Configure Sonarr
  ansible.builtin.include_tasks: sonarr.yml

- name: Configure Radarr
  ansible.builtin.include_tasks: radarr.yml

- name: Configure Prowlarr
  ansible.builtin.include_tasks: prowlarr.yml

- name: Configure Bazarr
  ansible.builtin.include_tasks: bazarr.yml
